name: sp500_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21,<1.26
  - pandas>=1.3,<2.1
  - scikit-learn>=1.0,<1.4
  - matplotlib>=3.4,<3.8
  - seaborn>=0.11,<0.13
  - xgboost>=1.5,<2.0
  - lightgbm>=3.3,<4.2
  - h5py>=3.6,<4.0
  - pytables>=3.6,<4.0
  - joblib>=1.0,<1.4
  - scipy>=1.7,<1.12
  - tqdm>=4.62,<5.0
  - shap>=0.40,<0.45
  - ta-lib
  - pip
  - pip:
      - boruta>=0.3,<0.4
      - yellowbrick>=1.3,<1.6
